-- MySQL Script generated by MySQL Workbench
-- Wed Nov  9 22:25:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CAPF
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS 'CAPF' ;

-- -----------------------------------------------------
-- Schema CAPF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'CAPF' DEFAULT CHARACTER SET utf8 ;
USE 'CAPF' ;

-- -----------------------------------------------------
-- Table 'CAPF'.'Usuario'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Usuario' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Usuario' (
  'cpf' INT NOT NULL,
  'nome' VARCHAR(45) NULL,
  'usuario' VARCHAR(45) NULL,
  'senha' VARCHAR(45) NULL,
  'tipo' INT(5) NULL,
  'creci' INT(20) NULL,
  PRIMARY KEY ('cpf'))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Adm'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Adm' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Adm' (
  'Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('Usuario_cpf'),
  CONSTRAINT 'fk_Adm_Usuario1'
    FOREIGN KEY ('Usuario_cpf')
    REFERENCES 'CAPF'.'Usuario' ('cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'UsuarioMasterFranqueado'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'UsuarioMasterFranqueado' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'UsuarioMasterFranqueado' (
  'Usuario_cpf' INT NOT NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('Usuario_cpf'),
  INDEX 'fk_UsuarioMasterFranqueado_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_UsuarioMasterFranqueado_Usuario1'
    FOREIGN KEY ('Usuario_cpf')
    REFERENCES 'CAPF'.'Usuario' ('cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_UsuarioMasterFranqueado_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Meta'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Meta' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Meta' (
  'id_meta' INT NOT NULL,
  'nome' VARCHAR(45) NULL,
  'tipo' INT NULL,
  'valor' VARCHAR(45) NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('id_meta'),
  INDEX 'fk_Meta_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Meta_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Franqueado'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Franqueado' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Franqueado' (
  'id_franqueado' INT NOT NULL,
  'nome_responsavel' VARCHAR(45) NULL,
  'nome_franquia' VARCHAR(45) NULL,
  'numero' INT NULL,
  'endereco' VARCHAR(45) NULL,
  'tel_franquia' INT NULL,
  'tel_responsavel' INT NULL,
  'cep' INT NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('id_franqueado'),
  INDEX 'fk_Franqueado_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Franqueado_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'MasterFranquia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'MasterFranquia' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'MasterFranquia' (
  'Franqueado_id_franqueado' INT NOT NULL,
  PRIMARY KEY ('Franqueado_id_franqueado'),
  CONSTRAINT 'fk_MasterFranquia_Franqueado1'
    FOREIGN KEY ('Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'Franqueado' ('id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'CategoriaKpi'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'CategoriaKpi' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'CategoriaKpi' (
  'id_categoria' INT NOT NULL,
  'nome' VARCHAR(45) NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  'MasterFranquia_Franqueado_id_franqueado' INT NOT NULL,
  PRIMARY KEY ('id_categoria'),
  INDEX 'fk_CategoriaKpi_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  INDEX 'fk_CategoriaKpi_MasterFranquia1_idx' ('MasterFranquia_Franqueado_id_franqueado' ASC) VISIBLE,
  CONSTRAINT 'fk_CategoriaKpi_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_CategoriaKpi_MasterFranquia1'
    FOREIGN KEY ('MasterFranquia_Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'MasterFranquia' ('Franqueado_id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Kpi'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Kpi' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Kpi' (
  'id_kpi' INT NOT NULL,
  'tipo' VARCHAR(45) NULL,
  'nome' VARCHAR(45) NULL,
  'valor' VARCHAR(45) NULL,
  'Meta_id_meta' INT NOT NULL,
  'CategoriaKpi_id_categoria' INT NOT NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('id_kpi'),
  INDEX 'fk_Kpi_Meta1_idx' ('Meta_id_meta' ASC) VISIBLE,
  INDEX 'fk_Kpi_CategoriaKpi1_idx' ('CategoriaKpi_id_categoria' ASC) VISIBLE,
  INDEX 'fk_Kpi_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Kpi_Meta1'
    FOREIGN KEY ('Meta_id_meta')
    REFERENCES 'CAPF'.'Meta' ('id_meta')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Kpi_CategoriaKpi1'
    FOREIGN KEY ('CategoriaKpi_id_categoria')
    REFERENCES 'CAPF'.'CategoriaKpi' ('id_categoria')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Kpi_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'UsuarioFranqueado'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'UsuarioFranqueado' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'UsuarioFranqueado' (
  'Usuario_cpf' INT NOT NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('Usuario_cpf'),
  INDEX 'fk_UsuarioFranqueado_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_UsuarioFranqueado_Usuario1'
    FOREIGN KEY ('Usuario_cpf')
    REFERENCES 'CAPF'.'Usuario' ('cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_UsuarioFranqueado_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'RegiaoBrasil'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'RegiaoBrasil' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'RegiaoBrasil' (
  'id_RegiaoBrasil' INT NOT NULL,
  'nome' VARCHAR(45) NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('id_RegiaoBrasil'),
  INDEX 'fk_RegiaoBrasil_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_RegiaoBrasil_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Estado'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Estado' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Estado' (
  'RegiaoBrasil_id_RegiaoBrasil' INT NOT NULL,
  'id_estado' INT NOT NULL,
  'nome' VARCHAR(45) NULL,
  'sigla' VARCHAR(45) NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('RegiaoBrasil_id_RegiaoBrasil', 'id_estado'),
  INDEX 'fk_Estado_RegiaoBrasil1_idx' ('RegiaoBrasil_id_RegiaoBrasil' ASC) VISIBLE,
  INDEX 'fk_Estado_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Estado_RegiaoBrasil1'
    FOREIGN KEY ('RegiaoBrasil_id_RegiaoBrasil')
    REFERENCES 'CAPF'.'RegiaoBrasil' ('id_RegiaoBrasil')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Estado_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Cidade'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Cidade' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Cidade' (
  'Estado_RegiaoBrasil_id_RegiaoBrasil' INT NOT NULL,
  'Estado_id_estado' INT NOT NULL,
  'id_cidade' INT NOT NULL,
  'nome' VARCHAR(30) NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('Estado_RegiaoBrasil_id_RegiaoBrasil', 'Estado_id_estado', 'id_cidade'),
  INDEX 'fk_Cidade_Estado1_idx' ('Estado_RegiaoBrasil_id_RegiaoBrasil' ASC, 'Estado_id_estado' ASC) VISIBLE,
  INDEX 'fk_Cidade_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Cidade_Estado1'
    FOREIGN KEY ('Estado_RegiaoBrasil_id_RegiaoBrasil' , 'Estado_id_estado')
    REFERENCES 'CAPF'.'Estado' ('RegiaoBrasil_id_RegiaoBrasil' , 'id_estado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Cidade_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Bairro'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Bairro' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Bairro' (
  'Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' INT NOT NULL,
  'Cidade_Estado_id_estado' INT NOT NULL,
  'Cidade_id_cidade' INT NOT NULL,
  'id_bairro' VARCHAR(45) NOT NULL,
  'nome' INT NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  PRIMARY KEY ('Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil', 'Cidade_Estado_id_estado', 'Cidade_id_cidade', 'id_bairro'),
  INDEX 'fk_Bairro_Cidade1_idx' ('Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' ASC, 'Cidade_Estado_id_estado' ASC, 'Cidade_id_cidade' ASC) VISIBLE,
  INDEX 'fk_Bairro_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  CONSTRAINT 'fk_Bairro_Cidade1'
    FOREIGN KEY ('Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' , 'Cidade_Estado_id_estado' , 'Cidade_id_cidade')
    REFERENCES 'CAPF'.'Cidade' ('Estado_RegiaoBrasil_id_RegiaoBrasil' , 'Estado_id_estado' , 'id_cidade')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Bairro_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'RegiaoFranquia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'RegiaoFranquia' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'RegiaoFranquia' (
  'nome' VARCHAR(30) NOT NULL,
  'Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' INT NOT NULL,
  'Bairro_Cidade_Estado_id_estado' INT NOT NULL,
  'Bairro_Cidade_id_cidade' INT NOT NULL,
  'Bairro_id_bairro' VARCHAR(45) NOT NULL,
  'Adm_Usuario_cpf' INT NOT NULL,
  'MasterFranquia_Franqueado_id_franqueado' INT NOT NULL,
  PRIMARY KEY ('nome'),
  INDEX 'fk_RegiaoFranquia_Bairro1_idx' ('Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' ASC, 'Bairro_Cidade_Estado_id_estado' ASC, 'Bairro_Cidade_id_cidade' ASC, 'Bairro_id_bairro' ASC) VISIBLE,
  INDEX 'fk_RegiaoFranquia_Adm1_idx' ('Adm_Usuario_cpf' ASC) VISIBLE,
  INDEX 'fk_RegiaoFranquia_MasterFranquia1_idx' ('MasterFranquia_Franqueado_id_franqueado' ASC) VISIBLE,
  CONSTRAINT 'fk_RegiaoFranquia_Bairro1'
    FOREIGN KEY ('Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' , 'Bairro_Cidade_Estado_id_estado' , 'Bairro_Cidade_id_cidade' , 'Bairro_id_bairro')
    REFERENCES 'CAPF'.'Bairro' ('Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil' , 'Cidade_Estado_id_estado' , 'Cidade_id_cidade' , 'id_bairro')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_RegiaoFranquia_Adm1'
    FOREIGN KEY ('Adm_Usuario_cpf')
    REFERENCES 'CAPF'.'Adm' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_RegiaoFranquia_MasterFranquia1'
    FOREIGN KEY ('MasterFranquia_Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'MasterFranquia' ('Franqueado_id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Franquia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Franquia' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Franquia' (
  'Franqueado_id_franqueado' INT NOT NULL,
  'creci' INT NULL,
  'cnpj' VARCHAR(45) NULL,
  'email' VARCHAR(45) NULL,
  'whatsapp' VARCHAR(45) NULL,
  'data_operacao' DATE NULL,
  'data_inauguracao' DATE NULL,
  'Franquiacol' VARCHAR(45) NULL,
  'incMunicipal' VARCHAR(45) NULL,
  'MasterFranquia_Franqueado_id_franqueado' INT NOT NULL,
  'RegiaoFranquia_nome' VARCHAR(30) NOT NULL,
  PRIMARY KEY ('Franqueado_id_franqueado'),
  INDEX 'fk_Franquia_Franqueado1_idx' ('Franqueado_id_franqueado' ASC) VISIBLE,
  INDEX 'fk_Franquia_MasterFranquia1_idx' ('MasterFranquia_Franqueado_id_franqueado' ASC) VISIBLE,
  INDEX 'fk_Franquia_RegiaoFranquia1_idx' ('RegiaoFranquia_nome' ASC) VISIBLE,
  CONSTRAINT 'fk_Franquia_Franqueado1'
    FOREIGN KEY ('Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'Franqueado' ('id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Franquia_MasterFranquia1'
    FOREIGN KEY ('MasterFranquia_Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'MasterFranquia' ('Franqueado_id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Franquia_RegiaoFranquia1'
    FOREIGN KEY ('RegiaoFranquia_nome')
    REFERENCES 'CAPF'.'RegiaoFranquia' ('nome')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'RegistroKpi'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'RegistroKpi' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'RegistroKpi' (
  'id_registro' INT NOT NULL,
  'Kpi_id_kpi' INT NOT NULL,
  'data' INT NULL,
  'status' INT(2) NULL,
  'valor' VARCHAR(45) NULL,
  'UsuarioFranqueado_Usuario_cpf' INT NOT NULL,
  'Franquia_Franqueado_id_franqueado' INT NOT NULL,
  INDEX 'fk_RegistroKpi_Kpi1_idx' ('Kpi_id_kpi' ASC) VISIBLE,
  PRIMARY KEY ('id_registro'),
  INDEX 'fk_RegistroKpi_UsuarioFranqueado1_idx' ('UsuarioFranqueado_Usuario_cpf' ASC) VISIBLE,
  INDEX 'fk_RegistroKpi_Franquia1_idx' ('Franquia_Franqueado_id_franqueado' ASC) VISIBLE,
  CONSTRAINT 'fk_RegistroKpi_Kpi1'
    FOREIGN KEY ('Kpi_id_kpi')
    REFERENCES 'CAPF'.'Kpi' ('id_kpi')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_RegistroKpi_UsuarioFranqueado1'
    FOREIGN KEY ('UsuarioFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_RegistroKpi_Franquia1'
    FOREIGN KEY ('Franquia_Franqueado_id_franqueado')
    REFERENCES 'CAPF'.'Franquia' ('Franqueado_id_franqueado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'MovimentoKpi'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'MovimentoKpi' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'MovimentoKpi' (
  'data' INT NULL,
  'id_movimento' INT NOT NULL,
  'UsuarioMasterFranqueado_Usuario_cpf' INT NOT NULL,
  'Meta_id_meta' INT NOT NULL,
  'RegistroKpi_id_registro' INT NOT NULL,
  INDEX 'fk_MovimentoKpi_UsuarioMasterFranqueado1_idx' ('UsuarioMasterFranqueado_Usuario_cpf' ASC) VISIBLE,
  PRIMARY KEY ('id_movimento'),
  INDEX 'fk_MovimentoKpi_Meta1_idx' ('Meta_id_meta' ASC) VISIBLE,
  INDEX 'fk_MovimentoKpi_RegistroKpi1_idx' ('RegistroKpi_id_registro' ASC) VISIBLE,
  CONSTRAINT 'fk_MovimentoKpi_UsuarioMasterFranqueado1'
    FOREIGN KEY ('UsuarioMasterFranqueado_Usuario_cpf')
    REFERENCES 'CAPF'.'UsuarioMasterFranqueado' ('Usuario_cpf')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_MovimentoKpi_Meta1'
    FOREIGN KEY ('Meta_id_meta')
    REFERENCES 'CAPF'.'Meta' ('id_meta')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_MovimentoKpi_RegistroKpi1'
    FOREIGN KEY ('RegistroKpi_id_registro')
    REFERENCES 'CAPF'.'RegistroKpi' ('id_registro')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Estado_has_RegiaoFranquia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Estado_has_RegiaoFranquia' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Estado_has_RegiaoFranquia' (
  'Estado_id_estado' INT NOT NULL,
  'RegiaoFranquia_nome' VARCHAR(30) NOT NULL,
  'data_associacao' DATE NULL,
  PRIMARY KEY ('Estado_id_estado', 'RegiaoFranquia_nome'),
  INDEX 'fk_Estado_has_RegiaoFranquia_RegiaoFranquia1_idx' ('RegiaoFranquia_nome' ASC) VISIBLE,
  INDEX 'fk_Estado_has_RegiaoFranquia_Estado_idx' ('Estado_id_estado' ASC) VISIBLE,
  CONSTRAINT 'fk_Estado_has_RegiaoFranquia_Estado'
    FOREIGN KEY ('Estado_id_estado')
    REFERENCES 'CAPF'.'Estado' ('id_estado')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Estado_has_RegiaoFranquia_RegiaoFranquia1'
    FOREIGN KEY ('RegiaoFranquia_nome')
    REFERENCES 'CAPF'.'RegiaoFranquia' ('nome')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table 'CAPF'.'Cidade_has_RegiaoFranquia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'CAPF'.'Cidade_has_RegiaoFranquia' ;

CREATE TABLE IF NOT EXISTS 'CAPF'.'Cidade_has_RegiaoFranquia' (
  'Cidade_id_cidade' INT NOT NULL,
  'RegiaoFranquia_nome' VARCHAR(30) NOT NULL,
  'data_associacao' DATE NULL,
  PRIMARY KEY ('Cidade_id_cidade', 'RegiaoFranquia_nome'),
  INDEX 'fk_Cidade_has_RegiaoFranquia_RegiaoFranquia1_idx' ('RegiaoFranquia_nome' ASC) VISIBLE,
  INDEX 'fk_Cidade_has_RegiaoFranquia_Cidade1_idx' ('Cidade_id_cidade' ASC) VISIBLE,
  CONSTRAINT 'fk_Cidade_has_RegiaoFranquia_Cidade1'
    FOREIGN KEY ('Cidade_id_cidade')
    REFERENCES 'CAPF'.'Cidade' ('id_cidade')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT 'fk_Cidade_has_RegiaoFranquia_RegiaoFranquia1'
    FOREIGN KEY ('RegiaoFranquia_nome')
    REFERENCES 'CAPF'.'RegiaoFranquia' ('nome')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
