-- MySQL Script generated by MySQL Workbench
-- Sat Nov 12 17:04:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema capf
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `capf` ;

-- -----------------------------------------------------
-- Schema capf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `capf` DEFAULT CHARACTER SET utf8 ;
USE `capf` ;

-- -----------------------------------------------------
-- Table `capf`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `capf`.`Usuario` (
  `cpf` BIGINT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `tipo` INT(5) NULL,
  `email` VARCHAR(60) NOT NULL,
  `creci` INT(20) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capf`.`Adm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Adm` ;

CREATE TABLE IF NOT EXISTS `capf`.`Adm` (
  `Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`Usuario_cpf`),
  CONSTRAINT `fk_Adm_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `capf`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capf`.`UsuarioMasterFranqueado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`UsuarioMasterFranqueado` ;

CREATE TABLE IF NOT EXISTS `capf`.`UsuarioMasterFranqueado` (
  `Usuario_cpf` BIGINT NOT NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`Usuario_cpf`),
  CONSTRAINT `fk_UsuarioMasterFranqueado_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `capf`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioMasterFranqueado_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `capf`.`UsuarioFranqueado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`UsuarioFranqueado` ;

CREATE TABLE IF NOT EXISTS `capf`.`UsuarioFranqueado` (
  `Usuario_cpf` BIGINT NOT NULL,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`Usuario_cpf`),
  CONSTRAINT `fk_UsuarioFranqueado_Usuario1`
    FOREIGN KEY (`Usuario_cpf`)
    REFERENCES `capf`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioFranqueado_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `capf`.`Meta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Meta` ;

CREATE TABLE IF NOT EXISTS `capf`.`Meta` (
  `id_meta` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `valor` VARCHAR(45) NULL,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`id_meta`),
  CONSTRAINT `fk_Meta_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `capf`.`Franqueado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Franqueado` ;

CREATE TABLE IF NOT EXISTS `capf`.`Franqueado` (
  `id_franqueado` INT NOT NULL AUTO_INCREMENT,
  `nome_responsavel` VARCHAR(45) NULL,
  `nome_franquia` VARCHAR(45) NULL,
  `numero` INT NULL,
  `endereco` VARCHAR(45) NULL,
  `tel_franquia` INT NULL,
  `tel_responsavel` INT NULL,
  `cep` INT NULL,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`id_franqueado`),
  CONSTRAINT `fk_Franqueado_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `capf`.`MasterFranquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`MasterFranquia` ;

CREATE TABLE IF NOT EXISTS `capf`.`MasterFranquia` (
  `Franqueado_id_franqueado` INT NOT NULL,
  PRIMARY KEY (`Franqueado_id_franqueado`),
  CONSTRAINT `fk_MasterFranquia_Franqueado1`
    FOREIGN KEY (`Franqueado_id_franqueado`)
    REFERENCES `capf`.`Franqueado` (`id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`Franquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Franquia` ;

CREATE TABLE IF NOT EXISTS `capf`.`Franquia` (
  `Franqueado_id_franqueado` INT NOT NULL,
  `creci` INT NULL,
  `cnpj` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `whatsapp` VARCHAR(45) NULL,
  `data_operacao` DATE NULL,
  `data_inauguracao` DATE NULL,
  `Franquiacol` VARCHAR(45) NULL,
  `incMunicipal` VARCHAR(45) NULL,
  `MasterFranquia_Franqueado_id_franqueado` INT NOT NULL,
  `RegiaoFranquia_id_RegiaoFranquia` INT NOT NULL,
  PRIMARY KEY (`Franqueado_id_franqueado`),
  CONSTRAINT `fk_Franquia_Franqueado1`
    FOREIGN KEY (`Franqueado_id_franqueado`)
    REFERENCES `capf`.`Franqueado` (`id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Franquia_MasterFranquia1`
    FOREIGN KEY (`MasterFranquia_Franqueado_id_franqueado`)
    REFERENCES `capf`.`MasterFranquia` (`Franqueado_id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Franquia_RegiaoFranquia1`
    FOREIGN KEY (`RegiaoFranquia_id_RegiaoFranquia`)
    REFERENCES `capf`.`RegiaoFranquia` (`id_RegiaoFranquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `capf`.`CategoriaKpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`CategoriaKpi` ;

CREATE TABLE IF NOT EXISTS `capf`.`CategoriaKpi` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  `MasterFranquia_Franqueado_id_franqueado` INT NOT NULL,
  PRIMARY KEY (`id_categoria`),
  CONSTRAINT `fk_CategoriaKpi_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CategoriaKpi_MasterFranquia1`
    FOREIGN KEY (`MasterFranquia_Franqueado_id_franqueado`)
    REFERENCES `capf`.`MasterFranquia` (`Franqueado_id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capf`.`Kpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Kpi` ;

CREATE TABLE IF NOT EXISTS `capf`.`Kpi` (
  `id_kpi` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NULL,
  `nome` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `Meta_id_meta` INT NOT NULL,
  `CategoriaKpi_id_categoria` INT NOT NULL,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`id_kpi`),
  CONSTRAINT `fk_Kpi_Meta1`
    FOREIGN KEY (`Meta_id_meta`)
    REFERENCES `capf`.`Meta` (`id_meta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kpi_CategoriaKpi1`
    FOREIGN KEY (`CategoriaKpi_id_categoria`)
    REFERENCES `capf`.`CategoriaKpi` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kpi_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `capf`.`RegiaoBrasil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`RegiaoBrasil` ;

CREATE TABLE IF NOT EXISTS `capf`.`RegiaoBrasil` (
  `id_RegiaoBrasil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`id_RegiaoBrasil`),
  CONSTRAINT `fk_RegiaoBrasil_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Estado` ;

CREATE TABLE IF NOT EXISTS `capf`.`Estado` (
  `RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sigla` VARCHAR(45) NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`RegiaoBrasil_id_RegiaoBrasil`, `id_estado`),
  CONSTRAINT `fk_Estado_RegiaoBrasil1`
    FOREIGN KEY (`RegiaoBrasil_id_RegiaoBrasil`)
    REFERENCES `capf`.`RegiaoBrasil` (`id_RegiaoBrasil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capf`.`Cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Cidade` ;

CREATE TABLE IF NOT EXISTS `capf`.`Cidade` (
  `Estado_RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `Estado_id_estado` INT NOT NULL,
  `id_cidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`Estado_RegiaoBrasil_id_RegiaoBrasil`, `Estado_id_estado`, `id_cidade`),
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_RegiaoBrasil_id_RegiaoBrasil` , `Estado_id_estado`)
    REFERENCES `capf`.`Estado` (`RegiaoBrasil_id_RegiaoBrasil` , `id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidade_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `capf`.`Bairro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Bairro` ;

CREATE TABLE IF NOT EXISTS `capf`.`Bairro` (
  `Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `Cidade_Estado_id_estado` INT NOT NULL,
  `Cidade_id_cidade` INT NOT NULL,
  `id_bairro` INT NOT NULL AUTO_INCREMENT,
  `nome` INT NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  PRIMARY KEY (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil`, `Cidade_Estado_id_estado`, `Cidade_id_cidade`, `id_bairro`),
  CONSTRAINT `fk_Bairro_Cidade1`
    FOREIGN KEY (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` , `Cidade_Estado_id_estado` , `Cidade_id_cidade`)
    REFERENCES `capf`.`Cidade` (`Estado_RegiaoBrasil_id_RegiaoBrasil` , `Estado_id_estado` , `id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bairro_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`RegistroKpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`RegistroKpi` ;

CREATE TABLE IF NOT EXISTS `capf`.`RegistroKpi` (
  `id_registro` INT NOT NULL AUTO_INCREMENT,
  `Kpi_id_kpi` INT NOT NULL,
  `data` INT NULL,
  `status` INT(2) NULL,
  `valor` VARCHAR(45) NULL,
  `UsuarioFranqueado_Usuario_cpf` BIGINT NOT NULL,
  `Franquia_Franqueado_id_franqueado` INT NOT NULL,
  PRIMARY KEY (`id_registro`),
  CONSTRAINT `fk_RegistroKpi_Kpi1`
    FOREIGN KEY (`Kpi_id_kpi`)
    REFERENCES `capf`.`Kpi` (`id_kpi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroKpi_UsuarioFranqueado1`
    FOREIGN KEY (`UsuarioFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegistroKpi_Franquia1`
    FOREIGN KEY (`Franquia_Franqueado_id_franqueado`)
    REFERENCES `capf`.`Franquia` (`Franqueado_id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`MovimentoKpi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`MovimentoKpi` ;

CREATE TABLE IF NOT EXISTS `capf`.`MovimentoKpi` (
  `data` INT NULL,
  `id_movimento` INT NOT NULL AUTO_INCREMENT,
  `UsuarioMasterFranqueado_Usuario_cpf` BIGINT NOT NULL,
  `Meta_id_meta` INT NOT NULL,
  `RegistroKpi_id_registro` INT NOT NULL,
  PRIMARY KEY (`id_movimento`),
  CONSTRAINT `fk_MovimentoKpi_UsuarioMasterFranqueado1`
    FOREIGN KEY (`UsuarioMasterFranqueado_Usuario_cpf`)
    REFERENCES `capf`.`UsuarioMasterFranqueado` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovimentoKpi_Meta1`
    FOREIGN KEY (`Meta_id_meta`)
    REFERENCES `capf`.`Meta` (`id_meta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovimentoKpi_RegistroKpi1`
    FOREIGN KEY (`RegistroKpi_id_registro`)
    REFERENCES `capf`.`RegistroKpi` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`RegiaoFranquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`RegiaoFranquia` ;

CREATE TABLE IF NOT EXISTS `capf`.`RegiaoFranquia` (
  `id_RegiaoFranquia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  `Adm_Usuario_cpf` BIGINT NOT NULL,
  `MasterFranquia_Franqueado_id_franqueado` INT NOT NULL,
  `Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `Bairro_Cidade_Estado_id_estado` INT NOT NULL,
  `Bairro_Cidade_id_cidade` INT NOT NULL,
  `Bairro_id_bairro` INT NOT NULL,
  PRIMARY KEY (`id_RegiaoFranquia`),
  CONSTRAINT `fk_RegiaoFranquia_Adm1`
    FOREIGN KEY (`Adm_Usuario_cpf`)
    REFERENCES `capf`.`Adm` (`Usuario_cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegiaoFranquia_MasterFranquia1`
    FOREIGN KEY (`MasterFranquia_Franqueado_id_franqueado`)
    REFERENCES `capf`.`MasterFranquia` (`Franqueado_id_franqueado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RegiaoFranquia_Bairro1`
    FOREIGN KEY (`Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` , `Bairro_Cidade_Estado_id_estado` , `Bairro_Cidade_id_cidade` , `Bairro_id_bairro`)
    REFERENCES `capf`.`Bairro` (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` , `Cidade_Estado_id_estado` , `Cidade_id_cidade` , `id_bairro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`Estado_has_RegiaoFranquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Estado_has_RegiaoFranquia` ;

CREATE TABLE IF NOT EXISTS `capf`.`Estado_has_RegiaoFranquia` (
  `Estado_RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `Estado_id_estado` INT NOT NULL,
  `RegiaoFranquia_id_RegiaoFranquia` INT NOT NULL,
  PRIMARY KEY (`Estado_RegiaoBrasil_id_RegiaoBrasil`, `Estado_id_estado`, `RegiaoFranquia_id_RegiaoFranquia`),
  CONSTRAINT `fk_Estado_has_RegiaoFranquia_Estado1`
    FOREIGN KEY (`Estado_RegiaoBrasil_id_RegiaoBrasil` , `Estado_id_estado`)
    REFERENCES `capf`.`Estado` (`RegiaoBrasil_id_RegiaoBrasil` , `id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_has_RegiaoFranquia_RegiaoFranquia1`
    FOREIGN KEY (`RegiaoFranquia_id_RegiaoFranquia`)
    REFERENCES `capf`.`RegiaoFranquia` (`id_RegiaoFranquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `capf`.`Cidade_has_RegiaoFranquia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `capf`.`Cidade_has_RegiaoFranquia` ;

CREATE TABLE IF NOT EXISTS `capf`.`Cidade_has_RegiaoFranquia` (
  `Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` INT NOT NULL,
  `Cidade_Estado_id_estado` INT NOT NULL,
  `Cidade_id_cidade` INT NOT NULL,
  `RegiaoFranquia_id_RegiaoFranquia` INT NOT NULL,
  PRIMARY KEY (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil`, `Cidade_Estado_id_estado`, `Cidade_id_cidade`, `RegiaoFranquia_id_RegiaoFranquia`),
  CONSTRAINT `fk_Cidade_has_RegiaoFranquia_Cidade1`
    FOREIGN KEY (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` , `Cidade_Estado_id_estado` , `Cidade_id_cidade`)
    REFERENCES `capf`.`Cidade` (`Estado_RegiaoBrasil_id_RegiaoBrasil` , `Estado_id_estado` , `id_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidade_has_RegiaoFranquia_RegiaoFranquia1`
    FOREIGN KEY (`RegiaoFranquia_id_RegiaoFranquia`)
    REFERENCES `capf`.`RegiaoFranquia` (`id_RegiaoFranquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------------------------------------------
CREATE INDEX `fk_UsuarioMasterFranqueado_Adm1_idx` ON `capf`.`UsuarioMasterFranqueado` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_UsuarioFranqueado_UsuarioMasterFranqueado1_idx` ON `capf`.`UsuarioFranqueado`  (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_Meta_UsuarioMasterFranqueado1_idx` ON `capf`.`Meta` (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_Franqueado_UsuarioMasterFranqueado1_idx` ON `capf`.`Franqueado` (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_Franquia_Franqueado1_idx` ON `capf`.`Franquia` (`Franqueado_id_franqueado` ASC);

CREATE INDEX `fk_Franquia_MasterFranquia1_idx` ON `capf`.`Franquia` (`MasterFranquia_Franqueado_id_franqueado` ASC);

CREATE INDEX `fk_Franquia_RegiaoFranquia1_idx` ON `capf`.`Franquia` (`RegiaoFranquia_id_RegiaoFranquia` ASC);

CREATE INDEX `fk_CategoriaKpi_UsuarioMasterFranqueado1_idx` ON `capf`.`CategoriaKpi` (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_CategoriaKpi_MasterFranquia1_idx` ON `capf`.`CategoriaKpi` (`MasterFranquia_Franqueado_id_franqueado` ASC);

CREATE INDEX `fk_Kpi_Meta1_idx` ON `capf`.`Kpi` (`Meta_id_meta` ASC);

CREATE INDEX `fk_Kpi_CategoriaKpi1_idx` ON `capf`.`Kpi` (`CategoriaKpi_id_categoria` ASC);

CREATE INDEX `fk_Kpi_UsuarioMasterFranqueado1_idx` ON `capf`.`Kpi` (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_RegiaoBrasil_Adm1_idx` ON `capf`.`RegiaoBrasil` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_Estado_RegiaoBrasil1_idx` ON `capf`.`Estado` (`RegiaoBrasil_id_RegiaoBrasil` ASC);

CREATE INDEX `fk_Estado_Adm1_idx` ON `capf`.`Estado` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_Cidade_Estado1_idx` ON `capf`.`Cidade` (`Estado_RegiaoBrasil_id_RegiaoBrasil` ASC, `Estado_id_estado` ASC);

CREATE INDEX `fk_Cidade_Adm1_idx` ON `capf`.`Cidade` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_Bairro_Cidade1_idx` ON `capf`.`Bairro` (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` ASC, `Cidade_Estado_id_estado` ASC, `Cidade_id_cidade` ASC);

CREATE INDEX `fk_Bairro_Adm1_idx` ON `capf`.`Bairro` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_RegiaoFranquia_Adm1_idx` ON `capf`.`RegiaoFranquia` (`Adm_Usuario_cpf` ASC);

CREATE INDEX `fk_RegiaoFranquia_MasterFranquia1_idx` ON `capf`.`RegiaoFranquia` (`MasterFranquia_Franqueado_id_franqueado` ASC);

CREATE INDEX `fk_RegiaoFranquia_Bairro1_idx` ON `capf`.`RegiaoFranquia` (`Bairro_Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` ASC, `Bairro_Cidade_Estado_id_estado` ASC, `Bairro_Cidade_id_cidade` ASC, `Bairro_id_bairro` ASC);

CREATE INDEX `fk_RegistroKpi_Kpi1_idx` ON `capf`.`RegistroKpi` (`Kpi_id_kpi` ASC);

CREATE INDEX `fk_RegistroKpi_UsuarioFranqueado1_idx` ON `capf`.`RegistroKpi` (`UsuarioFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_RegistroKpi_Franquia1_idx` ON `capf`.`RegistroKpi` (`Franquia_Franqueado_id_franqueado` ASC);

CREATE INDEX `fk_MovimentoKpi_UsuarioMasterFranqueado1_idx` ON `capf`.`MovimentoKpi` (`UsuarioMasterFranqueado_Usuario_cpf` ASC);

CREATE INDEX `fk_MovimentoKpi_Meta1_idx` ON `capf`.`MovimentoKpi` (`Meta_id_meta` ASC);

CREATE INDEX `fk_MovimentoKpi_RegistroKpi1_idx` ON `capf`.`MovimentoKpi` (`RegistroKpi_id_registro` ASC);

CREATE INDEX `fk_Estado_has_RegiaoFranquia_RegiaoFranquia1_idx` ON `capf`.`Estado_has_RegiaoFranquia` (`RegiaoFranquia_id_RegiaoFranquia` ASC);

CREATE INDEX `fk_Estado_has_RegiaoFranquia_Estado1_idx` ON `capf`.`Estado_has_RegiaoFranquia` (`Estado_RegiaoBrasil_id_RegiaoBrasil` ASC, `Estado_id_estado` ASC);

CREATE INDEX `fk_Cidade_has_RegiaoFranquia_RegiaoFranquia1_idx` ON `capf`.`Cidade_has_RegiaoFranquia` (`RegiaoFranquia_id_RegiaoFranquia` ASC);

CREATE INDEX `fk_Cidade_has_RegiaoFranquia_Cidade1_idx` ON `capf`.`Cidade_has_RegiaoFranquia` (`Cidade_Estado_RegiaoBrasil_id_RegiaoBrasil` ASC, `Cidade_Estado_id_estado` ASC, `Cidade_id_cidade` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
